#!/usr/bin/env python
"""Config-family selection: compute the CHEAP coherence C for candidate QUASR
devices (field + audit only, no neutronics), then tile the C axis roughly uniformly
and emit a sweep manifest. Compute C FIRST, then choose, so the family spans a real
range of C instead of clustering (per docs/EXPERIMENTAL_DESIGN.md).

Also appends the small blanket-factorization subset (2-3 configs re-run at the
thin/thick blankets with streams='both') so analyze_sweep can trace A(tau).

Usage:
  python select_configs.py --ids 59509 932746 ... --out configs/production.json
  python select_configs.py --auto 20 --out configs/production.json   # pick diverse candidates
"""
from __future__ import annotations

import argparse
import csv
import gzip
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent / "python"))

import quasr_loader as ql
import coherence_metrics as cm
import field_audit as fa
from biotsavart_field import CoilField

CAT = HERE.parent / "data" / "quasr" / "catalogue.csv.gz"


def catalogue_rows():
    with gzip.open(CAT, "rt") as f:
        return list(csv.DictReader(f))


def auto_candidates(n):
    """Pick a diverse candidate set from the catalogue: spread over nfp and qs_error
    (a proxy for shaping), so the resulting C axis is populated rather than clustered."""
    rows = [r for r in catalogue_rows() if r.get("ID")]
    # bucket by nfp, then within each spread over |qs_error|
    by_nfp = {}
    for r in rows:
        by_nfp.setdefault(int(float(r["nfp"])), []).append(r)
    picks = []
    for nfp, rs in sorted(by_nfp.items()):
        rs = sorted(rs, key=lambda r: abs(float(r["qs_error"])))
        idx = np.linspace(0, len(rs) - 1, max(1, n // len(by_nfp))).astype(int)
        picks += [int(float(rs[i]["ID"])) for i in np.unique(idx)]
    return picks[:n]


def compute_C(ID, class_map):
    """Load, audit (hard gate), compute C. Returns a dict or None if the audit fails
    / the device can't be loaded."""
    try:
        dev = ql.load_device(ID)
    except Exception as e:  # noqa
        print(f"  {ID}: load failed ({e})"); return None
    field = CoilField(dev.coils, meta=dev.meta)
    passed, audit = fa.audit_coilfield(field, dev)
    bflux = [c for c in audit["checks"] if c["name"] == "boundary_flux"][0]
    if not passed:
        print(f"  {ID}: AUDIT FAILED (B.n rms {bflux['value']:.2e}) -> excluded")
        return None
    xyz, w, _ = dev.source_sample()
    m = cm.coherence_metrics(field.bhat(xyz), pos=xyz, weights=w, frame="cylindrical")
    cls = class_map.get(str(ID), class_map.get(ID, dev.meta["symmetry_class"]))
    print(f"  {ID}: C={m['C']:.4f} nfp={dev.meta['nfp']} iota={dev.meta['iota']} "
          f"class={cls}  (B.n rms {bflux['value']:.1e})")
    return dict(id=ID, C=float(m["C"]), nfp=dev.meta["nfp"], iota=dev.meta["iota"],
                aspect=dev.meta["aspect"], symmetry_class=cls,
                anisotropy=float(m["anisotropy"]))


def tile_C(cands, n_tiles):
    """Pick n_tiles configs spread roughly uniformly along the C axis."""
    cands = sorted(cands, key=lambda c: c["C"])
    if len(cands) <= n_tiles:
        return cands
    targets = np.linspace(cands[0]["C"], cands[-1]["C"], n_tiles)
    chosen, used = [], set()
    for t in targets:
        i = min(range(len(cands)),
                key=lambda j: (abs(cands[j]["C"] - t), j in used))
        if i not in used:
            used.add(i); chosen.append(cands[i])
    return chosen


def build_manifest(chosen, n_blanket_subset=2):
    defaults = dict(particles=200000, batches=20, streams="free", blanket="baseline",
                    nR=48, nphi=96, nZ=48, scale_retries=3, lost_particle_max=50,
                    vr=False)
    configs = []
    for c in chosen:
        configs.append(dict(id=c["id"], symmetry_class=c["symmetry_class"],
                            C_predicted=round(c["C"], 4)))
    # blanket-factorization subset: take a few spread-in-C configs, run BOTH streams
    # at baseline/thin/thick to trace A(tau) and test eta_source(C) invariance
    sub = tile_C(chosen, min(n_blanket_subset, len(chosen)))
    for c in sub:
        for blk in ("baseline", "thin", "thick"):
            configs.append(dict(id=c["id"], symmetry_class=c["symmetry_class"],
                                blanket=blk, streams="both",
                                C_predicted=round(c["C"], 4),
                                _note="blanket-factorization subset"))
    return dict(
        _comment="Auto-generated by select_configs.py. C_predicted is the cheap "
                 "field-only prediction; the sweep measures eta to test it.",
        defaults=defaults, configs=configs)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ids", type=int, nargs="*", default=None)
    ap.add_argument("--auto", type=int, default=None, help="auto-pick N diverse candidates")
    ap.add_argument("--tiles", type=int, default=12, help="configs in the C-scan")
    ap.add_argument("--class-map", default=None, help="JSON {id: 'QA'|'QH'|'QI'}")
    ap.add_argument("--out", default="configs/production.json")
    args = ap.parse_args()

    class_map = json.loads(Path(args.class_map).read_text()) if args.class_map else {}
    ids = args.ids or (auto_candidates(args.auto) if args.auto else [])
    if not ids:
        ap.error("give --ids or --auto N")
    print(f"[select] computing C for {len(ids)} candidates ...")
    cands = [c for c in (compute_C(i, class_map) for i in ids) if c]
    if not cands:
        ap.error("no candidates passed the field audit")
    chosen = tile_C(cands, args.tiles)
    man = build_manifest(chosen)
    outp = Path(args.out); outp.parent.mkdir(parents=True, exist_ok=True)
    outp.write_text(json.dumps(man, indent=2))
    Cs = sorted(c["C"] for c in chosen)
    print(f"[select] wrote {outp}: {len(chosen)} C-scan configs "
          f"(C in [{Cs[0]:.3f},{Cs[-1]:.3f}]) + blanket subset. "
          f"Set sbatch --array=0-{len(man['configs'])-1}.")


if __name__ == "__main__":
    main()
